### PR TITLE
fix: prevent accepting invitation before event resolves

### LINKED ISSUE #104: Accepting invitation before event resolves creates corrupted calendar reference
## Description

In `src/stores/invitations.ts`, `acceptInvitation()`  builds an event reference using data from the invitation's resolved event:

```typescript
acceptInvitation: async (giftWrapId, calendarId) => {
  const invitation = invitations.find((i) => i.giftWrapId === giftWrapId);
  if (!invitation) return;

  const eventRef = buildEventRef({
    kind: invitation.kind,
    authorPubkey: invitation.event?.user || "",  // ← empty string if event not resolved
    eventDTag: invitation.eventId,
    relayUrl: invitation.relayHint,
    viewKey: invitation.viewKey,
  });

  await useCalendarLists.getState().addEventToCalendar(calendarId, eventRef);
```

Invitations are fetched from gift wraps, and then their actual private events are resolved asynchronously in `processBuffer()` (runs on a 5-second timer). If a user accepts an invitation **before** the event has been fetched and decrypted, `invitation.event` is `undefined`, and the `authorPubkey` falls back to `""`.

This creates a malformed event coordinate like `32678::eventId` (missing author pubkey between the colons). This corrupted reference is then:
1. Published to relays as part of the calendar list
2. Permanently stored in the user's calendar
3. Never matchable by `fetchPrivateEvents()` (which expects valid coordinates)

## Impact

- The accepted event becomes permanently invisible so it's in the calendar list but can never be fetched
- The corrupted reference persists across sessions and devices
- No error or warning is shown to the user

### PR DESCRIPTION
**Pull request by Sky-walkerX**
Fixes #104.

### CODE REVIEW

File: src/stores/invitations.ts [hunk 1]
```diff
@@ -253,11 +253,19 @@ export const useInvitations = create<InvitationsState>((set, get) => ({
     const invitation = invitations.find((i) => i.giftWrapId === giftWrapId);
     if (!invitation) return;
 
+    // Guard: don't accept until the private event has been resolved,
+    // otherwise the author pubkey is missing and the event coordinate
+    // becomes malformed (e.g. "32678::dTag" instead of "32678:pubkey:dTag").
+    if (!invitation.event?.user) {
+      console.warn("Cannot accept invitation: event not yet resolved");
```
Comment (geralt-debugs) [inline src/stores/invitations.ts:260]: good catch. however, we can also disable the add to calendar button itself unless the event is resolved in the UI. Otherwise the user will click on the button and nothing will happen, which might seem like a bug

**Review by geralt-debugs — APPROVED** [review]
